name: Branch CI

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"
  COVERAGE_THRESHOLD: "0"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install base dependencies first, including lib-ml and lib-version from requirements.txt
          pip install -r requirements.txt
          # Install development and testing tools
          pip install pytest coverage pytest-cov pylint memory-profiler

      - name: Pylint (warnings break the build)
        run: |
          # Assuming the main service code is in the 'app' directory relative to the repo root
          # Adjust if your source code structure is different
          pylint app

      - name: Unit tests + coverage
        run: |
          # Run tests with coverage for the 'app' directory
          coverage run --source=app -m pytest tests/ -v
          coverage report
          coverage xml
          # Extract coverage percentage from the report
          COVERAGE=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "COVER=$COVERAGE" >> $GITHUB_ENV
          echo "Code coverage: $COVERAGE%"

      - name: Fail if coverage below threshold
        run: |
          python - << 'PY'
          import os, sys
          cov = float(os.environ.get("COVER", "0"))
          thr = float(os.environ["COVERAGE_THRESHOLD"])
          print(f"Code Coverage: {cov:.1f}% (Threshold: {thr}%)")
          if cov < thr:
              sys.exit(f"Coverage {cov:.1f}% is below the threshold {thr}%")
          PY